"""Step 5: on a passing conversion, raise a PR with the converted notebook.

Uses the `gh` CLI against the current git repo (test with VS Code + your personal
GitHub, per Manas). dry_run=True writes the file and prints the git/gh commands
without touching any remote.
"""
from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path

from accelerator.config import REPO_ROOT, SETTINGS
from usecases.code_migration.config import CONVERTED_DIR


@dataclass
class PRResult:
    raised: bool
    detail: str
    branch: str
    file: Path


def _git(args: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=REPO_ROOT, text=True, capture_output=True, check=check)


def _has_gh() -> bool:
    import shutil

    return shutil.which("gh") is not None


def write_converted(example_key: str, code: str) -> Path:
    CONVERTED_DIR.mkdir(parents=True, exist_ok=True)
    out = CONVERTED_DIR / f"{example_key}_transform.py"
    header = (
        f"# Auto-generated by lakebase code_migration accelerator.\n"
        f"# Source example: {example_key}. Validated by dual-run against a data sample.\n"
        f"# Human review required before merge.\n\n"
    )
    out.write_text(header + code + "\n")
    return out


def raise_pr(example_key: str, code: str, summary: str, dry_run: bool = True) -> PRResult:
    out = write_converted(example_key, code)
    branch = f"migrate/{example_key}-to-pyspark"
    rel = out.relative_to(REPO_ROOT)

    if dry_run:
        detail = (
            "[dry-run] would run:\n"
            f"  git checkout -b {branch}\n"
            f"  git add {rel}\n"
            f'  git commit -m "Convert {example_key} -> Databricks PySpark"\n'
            f"  git push -u origin {branch}\n"
            f"  gh pr create --base {SETTINGS.pr_base_branch} --title ... --body ..."
        )
        return PRResult(False, detail, branch, out)

    if not _has_gh():
        return PRResult(False, "gh CLI not found; install it or use dry_run.", branch, out)

    _git(["checkout", "-b", branch])
    _git(["add", str(rel)])
    _git(["commit", "-m", f"Convert {example_key} -> Databricks PySpark (validated)"])
    push = _git(["push", "-u", "origin", branch], check=False)
    if push.returncode != 0:
        return PRResult(False, f"git push failed: {push.stderr.strip()}", branch, out)

    body = f"Automated conversion validated by dual-run on a data sample.\n\n{summary}"
    pr = subprocess.run(
        ["gh", "pr", "create", "--base", SETTINGS.pr_base_branch,
         "--title", f"Convert {example_key} -> Databricks PySpark", "--body", body],
        cwd=REPO_ROOT, text=True, capture_output=True,
    )
    if pr.returncode != 0:
        return PRResult(False, f"gh pr create failed: {pr.stderr.strip()}", branch, out)
    return PRResult(True, pr.stdout.strip(), branch, out)
